# Provisioning of several disk for each container
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azuredevopsdeployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azuredevopsapp
    spec:
      containers:
      - name: azuredevopsapp
        image: aksacrhakki2.azurecr.io/azuredevopsdemo:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: azuredevopsapplb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azuredevopsapp
